files:
  - source: /**/res/values/strings.xml
    translation: /**/res/values-%locale%/strings.xml
    languages_mapping:
      locale:
        fr: fr
        de: de
        pt-BR: pt-br
        es-ES: es-es
        it: it
        ja: ja
